# number of slot
NUM_SLOTS = 10
BATCH_SIZE = 100
NUM_MAX_STEPS = 1000
MEMORY_CAPACITY = 2000

# Network
INPUT_LAYER_SIZE = 2 + NUM_SLOTS + int(NUM_SLOTS * (NUM_SLOTS - 1) / 2)
OUTPUT_LAYER_SIZE = int(NUM_SLOTS * (NUM_SLOTS - 1) / 2)
MID1_LAYER_SIZE = OUTPUT_LAYER_SIZE
MID2_LAYER_SIZE = OUTPUT_LAYER_SIZE

# path of DQN model
DQN_MODEL_FILEPATH = '../model/DQN.model'